# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-29 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0003_auto_20171029_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke',
            old_name='poker',
            new_name='user',
        ),
    ]
